### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by m521521l** [iFindTA/NHNewsBoardPro#1]
运行报各种错误  ，能解决下吗

**Comment by namo-py** [comment]
工程配置错误吧？你可以在stackoverflow上查看一些怎么配置处理相关的错误

参考办法：很可能是你选择的编译版本的问题，报错“找不到对应平台下的神马东东之类的”吧，在project navigation界面选中pod project，build setting里的Valid Architectures 增加你要的版本 then clean&&build即可
