### ISSUE TITLE
不能用！

### ISSUE THREAD

**Issue by 977616908** [iFindTA/NHNewsBoardPro#2]
您好，感谢你的分享。
问题:当我下载下来后，pod update，pod install 后提示ld: library not found for -lAFNetworking。
运行不了，您能帮我测试下吗？

----sundy
email:977616908@qq.com

**Comment by namo-py** [comment]
嗯，这个是配置的问题，你先按照优格issues的给出解决方案，稍候空闲了我会更新一下，最近太忙抱歉
https://github.com/iFindTA/NHNewsBoardPro/issues/1

2016-06-13 8:13 GMT+08:00 977616908 notifications@github.com:

**Comment by 977616908** [comment]
谢谢，期待您的更新！
ps：优格issues指的是什么？

**Comment by namo-py** [comment]
已经更新了，如果还不可以，可以尝试clean project ，and build again！

在 2016年6月13日 上午9:24，胡家驹 nanhujiaju@gmail.com写道：
